name: release{{@if(it.shouldPublishNpm)}}-publish{{/if}}

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Required permission: github repo => settings => actions => Allow GitHub Actions to create and approve pull requests
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: {{'${{ secrets.GITHUB_TOKEN }}'}}
          release-type: node
{{-@if(it.shouldPublishNpm)}}
    outputs:
      release_created: {{'${{ steps.release.outputs.release_created }}'}}
  
  publish:
    needs: release
    if: {{'${{ needs.release.outputs.release_created }}'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Publish to NPM
        # The --no-git-checks flag is needed to bypass an issue with pnpm related to GitHub's detached HEAD state during releases.
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: {{'${{ secrets.NPM_TOKEN }}'}}
{{-/if}}
